language: csharp
solution: Symitar.sln
env:
  global:
  - secure: "C9FBBcoGzIoOd3HFZPFGTOdbyrHQAx/BgtFeGwwUU429P6lMW5o3r7ThHvwLRkP9WQIcqYIAu9L/BQF+FaBzlZR8EK8LBrBOTPmzIQr1brCT0YiQeYrKwquhqSFp8gJxDflRcwKWcoCuIxMm2+rDKv7BcJFR9ixh0Sp8TMuHRxU="
  
install:
- nuget restore coveralls.net.sln
addons:
  coverity_scan:
    project:
      name: jdeering/SymSharp
      description: Build submitted via Travis CI
    notification_email: jason@deering.me
    build_command_prepend: msbuild /t:Clean
    build_command: msbuild /t:Rebuild
    branch_pattern: coverity_scan
