version: 1.4.{build}

configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

skip_tags: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: yI/MhDA4hPGJ+e1WHNBNYzFbgVgNR7owW+/2n60jIGdwYROHLyYz+7vVQPTDCrK3

nuget:
  disable_publish_on_pr: true

build:
  project: Symitar.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

deploy:
- provider: NuGet
  api_key:
    secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61
  on:
    branch: master